### ISSUE TITLE
paracraft窗口改变引起浏览器页面跟窗口分离

### ISSUE THREAD

**Issue by Elshadow** [NPLPackages/NplCefBrowser#3]
paracraft默认启动时候，非全屏显示的，然后切换全屏之后，cefbrowser就出现页面跟窗口分离的情况

**Comment by zhangleio** [comment]
Fixed,please update [NplCefBrowser v0.3.0](https://github.com/NPLPackages/NplCefBrowser/releases/download/0.3.0/NplCefBrowser.zip)

**Comment by Elshadow** [comment]
thanks,fixed confirmed
